name: CI # Continuous Integration

on:
    push:
        branches:
            - main
    pull_request:
    workflow_dispatch:

jobs:
    build-and-test:
        name: Tests on ${{ matrix.os }} with NodeJS-22

        strategy:
            matrix:
                os:
                    - ubuntu-latest
                    - windows-latest
                    - macos-latest

            fail-fast: true

        runs-on: ${{ matrix.os }}

        steps:
            -   uses: actions/checkout@v4
            -   uses: pnpm/action-setup@v4
                with:
                    version: 9

            -   name: Setup Node.js
                uses: actions/setup-node@v5
                with:
                    node-version: 22
                    cache: 'pnpm'

            -   name: Install
                run: pnpm i --frozen-lockfile

            -   name: Build
                run: pnpm build

            -   name: Test
                run: pnpm test
